### ISSUE TITLE
Does this use a Pepper?

### ISSUE THREAD

**Issue by lil5** [danang-id/simple-crypto-js#1]
I'm not very good with understanding crypto but have created a pouchdb plugin for my project.

I'd like to know if pepper is used in this lib.
(I couldn't find it in a variable by the name pepper.)

**Comment by lil5** [comment]
If [no, or no answer] I take it Cryptojs; AES, Hash and Salt is enough encryption

**Comment by danang-id** [comment]
@lil5 No, it don't use pepper.

**Comment by lil5** [comment]
Thanks for the reply
