### ISSUE TITLE
sign & verify messages?

### ISSUE THREAD

**Issue by pwFoo** [danang-id/simple-crypto-js#10]
Is it possible to sign & verify messages without encrypt it?

**Comment by danang-id** [comment]
@pwFoo At the moment, it is not possible. The goal of this package is to make encryption process simplified as much as possible. And I believe data signing will requires more effort as it needs to handle private and public key required for sign and verify the data. While this is fine is server side, this is not recommended to be done in the client side as private key required for data signing feature should be made public. Unless client version of this package should be made only for verifying data, but creating those different version will only create inconsistent features of a package. So, I think we should stick to current goal.
