### ISSUE TITLE
SimpleCrypto is Vulnerable to Chosen-Ciphertext Attacks

### ISSUE THREAD

**Issue by paragonie-scott** [danang-id/simple-crypto-js#12]
https://github.com/danang-id/simple-crypto-js/blob/b4263e62a86700fb923ea20d63162303ab8cb8ba/src/SimpleCrypto.ts#L29-L53

`SimpleCrypto` implements AES-CBC with PKCS#7 padding, which is [vulnerable to chosen-ciphertext attacks](https://paragonie.com/blog/2015/05/using-encryption-and-authentication-correctly), specifically a [padding oracle attack](https://robertheaton.com/2013/07/29/padding-oracle-attack/).

These vulnerabilities in CBC mode have been public for 17 years (since Serge Vaudenay published a paper about it in 2002).

Recommendation: Migrate to one of the following...

1. [XChaCha20-Poly1305](https://github.com/paragonie/sodium-plus/blob/master/docs/SodiumPlus/AEAD.md#aead)
2. [AES-GCM-SIV](https://tools.ietf.org/html/rfc8452)
3. [AES-GCM](https://tools.ietf.org/html/rfc5288)

**Comment by danang-id** [comment]
@paragonie-scott Thanks for the recommendation. Should have been considered before. I'll try to implements a better algorithm.

**Comment by paragonie-scott** [comment]
If you don't have any of the algorithms available to you, you might have to follow in the footsteps of @defuse and implement AES-CTR + HMAC-SHA2 (Encrypt then MAC) as detailed [here](https://github.com/defuse/php-encryption/blob/master/docs/CryptoDetails.md).

It's less simple internally, but it'll remain simple for your users.

**Comment by huntr-helper** [comment]
👋 Hey! We've recently opened a bug bounty against this issue, so if you want to get rewarded 💰 for fixing this vulnerability 🕷, head over to https://huntr.dev!

**Comment by syllasrangel** [comment]
Hey, guys. I'm facing the following problem: if I add any characters to the end of an encrypted string, the decrypt function will still decrypt correctly. This is a huge problem for me because I'm using the simpleCrypto to generate a unique code and I cannot have two different encrypted strings resulting in the same decrypted object.

**Comment by JamieSlome** [comment]
See https://github.com/danang-id/simple-crypto-js/pull/17 for a suggested fix.

**Comment by danang-id** [comment]
Sorry for very late reply. Already merged #17.

**Comment by danang-id** [comment]
NPM release should be available in a moment.
