### ISSUE TITLE
BUG: SimpleCrypto sees two numbers at the beginning of a string and encrypts it as a number, cutting off the rest of the string.

### ISSUE THREAD

**Issue by TransmissionsDev** [danang-id/simple-crypto-js#19]
Hey SimpleCrypto team,

I've been using this library for a while now, and was excited to see a new release, but my tests are failing as I've found a little bug in the type detection.

If I encrypt this string: `97c9fadd9deefa0e3594d79e6b86b55bb4906fc2ae21956ca09cdd51e6827a1e` using this function:
```js
 const simpleCrypto = new SimpleCrypto(password);

 return simpleCrypto.encrypt(data);
```

and decrypt it using:
```js
 try {
    const simpleCrypto = new SimpleCrypto(password);

    return simpleCrypto.decrypt(text);
  } catch {
    return undefined;
  }
```

I will get back the number `97` in number form (not string).

**If you need help reproducing, I can create a codesandbox or something, but this is a pretty easy to repo issue.**

**Comment by TransmissionsDev** [comment]
I would suggest adding another test string that starts with a number to ensure this issue doesn't occur again in the future 😄

**Comment by danang-id** [comment]
Yup, I believe this error is related to the new type detection mechanism on decryption process.

**Comment by danang-id** [comment]
> (Would be happy to make PR once this is fixed, just don't know the inner workings of how you guys do type detection)

For now, number type detection relies on native parseInt and isNaN API. I believe the logic shall need improvement.

**Comment by TransmissionsDev** [comment]
@danang-id Ah, found it. Yeah it's a weird quirk of `parseInt`, it just chops off the rest of a string if it starts with a number. Found a function that doesn't have this issue:

```function isNumber(n) { return /^-?[\d.]+(?:e-?\d+)?$/.test(n); } ```

**Comment by danang-id** [comment]
I believe the regular expression test, along with isNaN and parseFloat will do.

**Comment by danang-id** [comment]
Would you like to create a PR with the fix and the test? I think this will do.

```typescript
    return /^-?[\d.]+(?:e-?\d+)?$/.test(src) && !isNaN(parseFloat(src)) ? parseFloat(src) : src
```

**Comment by TransmissionsDev** [comment]
@danang-id Alright. I'll leave this issue open until the PR is merged, unless you wish to do otherwise.

**Comment by danang-id** [comment]
I will create a new NPM release patch soon with this fix.

**Comment by TransmissionsDev** [comment]
@danang-id Great to hear! Happy I could help, have a great day and thanks for making such a fantastic library!

**Comment by danang-id** [comment]
@TransmissionsDev Sure, thank you for pointing out this issue. Release version [2.4.1](https://www.npmjs.com/package/simple-crypto-js/v/2.4.1) is now available with this fix.
