### ISSUE TITLE
Empty string encryption

### ISSUE THREAD

**Issue by TransmissionsDev** [danang-id/simple-crypto-js#21]
The line here prevents us from encrypting an empty string, even though it was possible before 2.4.0?

https://github.com/danang-id/simple-crypto-js/blob/0ccd426da747a0f0c19e8c6fbc856b96c381c116/src/SimpleCrypto.ts#L51

I understand the reasoning behind this (as to prevent silly errors by developers), but this actually complicates my use case of doing E2EE, as live editing forms where users may clear a form, will throw an error.

Is there anyway I could make a PR that would disable this protection or at least add an an optional parameter to disable it?

**Comment by danang-id** [comment]
Yup, this is come after 2.4.0 update with the assumption that empty string is not subject to encryption. I could agree to disable empty string check. As the goals of this library is to be simple, I don't see an optional configuration is coming. 

Beside that snippet you provide, empty string check happens 3 times here.

https://github.com/danang-id/simple-crypto-js/blob/0ccd426da747a0f0c19e8c6fbc856b96c381c116/src/SimpleCrypto.ts#L51

https://github.com/danang-id/simple-crypto-js/blob/0ccd426da747a0f0c19e8c6fbc856b96c381c116/src/SimpleCrypto.ts#L172-L174

https://github.com/danang-id/simple-crypto-js/blob/0ccd426da747a0f0c19e8c6fbc856b96c381c116/src/SimpleCrypto.ts#L206-L208

You may, if you wish, provide a PR to remove empty string check.

**Comment by TransmissionsDev** [comment]
@danang-id Thank you! PR coming shortly. 😁

**Comment by TransmissionsDev** [comment]
@danang-id As I began working on this PR i noticed that this snippet you linked me:
https://github.com/danang-id/simple-crypto-js/blob/0ccd426da747a0f0c19e8c6fbc856b96c381c116/src/SimpleCrypto.ts#L172-L174

Isn't validating whether a plain string is empty, but whether the cypher text is empty. I don't think I should remove this, correct?

**Comment by danang-id** [comment]
Merged PR #22

**Comment by danang-id** [comment]
> This snippet isn't validating whether a plain string is empty, but whether the cypher text is empty. I don't think I should remove this, correct?

@TransmissionsDev The empty string check of `_dataBuffer` in `_decrypt()` is actually useless because of the `_dataBuffer` length check that happens after the empty string check.


https://github.com/danang-id/simple-crypto-js/blob/0ccd426da747a0f0c19e8c6fbc856b96c381c116/src/SimpleCrypto.ts#L176-L178

Anyway, I will also remove this check in 2.4.2.

**Comment by TransmissionsDev** [comment]
@danang-id Right. However, I would say that you could keep that check, as it provides useful debugging info. It's helpful to know the cipher text is empty vs it being too short.

**Comment by TransmissionsDev** [comment]
@danang-id Thanks for all your hard work, and thanks for being so quick to respond. Closing this PR as no further work needs to be done. 👍
