### ISSUE TITLE
Error: Unable to resolve module `crypto` from `node_modules/simple-crypto-js/node_modules/crypto-js/core.js`: crypto could not be found within the project

### ISSUE THREAD

**Issue by bhuvin25** [danang-id/simple-crypto-js#23]

**Comment by danang-id** [comment]
Please give a description about the error you are having, and also the steps to reproduce the error. Less information provided, less solution comes.

**Comment by danang-id** [comment]
@bhuvin25 If you are having this problem when in React Native, Expo, or IE 10 environment, please consult issue #24. 

Closing this for now.

**Comment by danang-id** [comment]
@bhuvin25 SimpleCrypto v2.5.0 is now available with compatibility support for IE 10 and React Native. Please do upgrade because v2.2.0 is vulnerable.
