### ISSUE TITLE
Cannot use namespace 'WordArray' as a type - TypeScript 3

### ISSUE THREAD

**Issue by mshaikh7** [danang-id/simple-crypto-js#34]
Hi Guys ...  I am trying to use simple-crypto-js lib in my angular app but while installing the package via npm i ... I am getting below Typescript errors - Cannot use namespace 'WordArray' as a type.

Below are the version details:
Angular 7
Typescript 3.2
Simple-crypto-js 2.3

Any help or guidance would be highly appreciated. Thank you!

![image](https://user-images.githubusercontent.com/39570480/102911019-191fa780-4441-11eb-8f77-76e5a99fc76a.png)

**Comment by danang-id** [comment]
Hi, @mshaikh7! 

Do you still need help regarding this issue? Sorry about this very late reply. This project currently not in active maintenance.
