### ISSUE TITLE
Malformed UTF-8 data

### ISSUE THREAD

**Issue by ronastlelobo** [danang-id/simple-crypto-js#6]
I am reading a .mp4 file and encrypting it using the library and writing it as a .dat file. I am accessing the .dat file and streaming 4,000,000 characters at a time till the end. While streaming, i am decrypting the data on go. So, the first set of characters are decrypting succcessfully using this method

  `var decipherText = simpleCrypto.decrypt(chunk)`  

while the next set of characters throw `Malformed UTF-8 data` error.

**Comment by kkrupovich** [comment]
almost same here - trying to encrypt private key and get 1 time of each ~5 malformed utf-8 data.

**Comment by danang-id** [comment]
@ronastlelobo @kkrupovich I'm sorry for very late response. If you may, could you provide the steps to recreate the case? This may be a bug on byte arrays parsing when decrypting.

**Comment by paulocastellano** [comment]
@danang-id 

I have same problem:

JSON:
```
{"user_id":"127382173821","user_name":"Paulo","user_email":"paulo@gmail.com","user_avatar":"https://link.to.user.avatar.com/image.jpg","custom_data":{"Job_Role":"CEO","Plan":"Pro","teammates":"4","Monthly_Spend":"50 USD"}}
```

How i encrypt:

```
let simpleCrypto = new SimpleCrypto(process.env.SECRET_KEY);
let uri = simpleCrypto.encrypt(JSON.stringify('MY_JSON_HERE'));
```

**Comment by Kwaysi** [comment]
Thanks encodeURIComponent worked for me too.

**Comment by irfannurzaman** [comment]
why can't encrypt in local storage be decrypted?

**Comment by danang-id** [comment]
@irfannurzaman Please make sure the data you are trying to get is an actual ciphered text. Otherwise, please open a new issue and provide a technical details or any log about the error.

I'll close the issue for now since it has been solved for a while.
